### ISSUE TITLE
[Panic] PantaLab(m04) panics during onBeat

### ISSUE THREAD

**Issue by simonzg** [meterio/meter-pov#26]
m04 panics during a normal onBeat.

Related logs:

```
t=2023-02-15T11:12:28+0000 lvl=info msg="Epoch updated" pkg=reactor from=21768 to=21769
t=2023-02-15T11:12:28+0000 lvl=info msg="Powpool prepare to add kframe, and notify PoW chain to pick head" pkg=reactor powHeight=1313117 powRawBlock=000000205d549fdea29a98352e019ba8b4a0ec7e40b5fec1709b7e29a3a3850100000000a69dad6d90af98c2b3bf6ecadce5b7900b42ed2c8b69a911b25c32416af74213e3bdec639eb2001d1b4823c30101000000010000000000000000000000000000000000000000000000000000000000000000ffffffff3c045d09140004e3bdec63087800000000000000283061423564644136663039364531323741463734643462363441313031616336433433464131323800000000030000000000000000266a24aa21a9ede2f61c3f71d1defd3fa999dfa36953755c690689799962b48bebd836974e8cf900000000000000001976a9143dbaaf6e48506cc955efaadb0e4769548c3e9a2d88ac00000000000000001976a9143dbaaf6e48506cc955efaadb0e4769548c3e9a2d88ac00000000
t=2023-02-15T11:12:28+0000 lvl=info msg="Powpool wash" pkg=powpool
t=2023-02-15T11:12:28+0000 lvl=info msg="added pow kframe" pkg=powpool powHeight=1313117
t=2023-02-15T11:12:28+0000 lvl=info msg="Powpool initial added kframe" pkg=reactor bestKblock=33629618 powHeight=1313117
t=2023-02-15T11:12:28+0000 lvl=info msg="I am in committee!!!" pkg=reactor
t=2023-02-15T11:12:28+0000 lvl=info msg="Replay pow blocks" pkg=reactor fromHeight=1313118
t=2023-02-15T11:12:28+0000 lvl=info msg="Pow replay done" pkg=powpool start=1313118 end=1313117
t=2023-02-15T11:12:28+0000 lvl=info msg="start to execute cmd" pkg=pacemaker cmd=Reboot
t=2023-02-15T11:12:28+0000 lvl=info msg="bestQC and bestBlock matches" pkg=reactor bestQC=33629618 bestBlock=33629618
t=2023-02-15T11:12:28+0000 lvl=info msg="--- Pacemaker stopped successfully, REBOOT now" pkg=pacemaker
t=2023-02-15T11:12:28+0000 lvl=info msg="*** Pacemaker start with height 33629618, round 0" pkg=pacemaker qc=QC(H:33629618,R:1956,E:21768) calcStatsTx=true mode=Normal
t=2023-02-15T11:12:28+0000 lvl=info msg="committee initialized already" pkg=reactor nonce=3273869339 kBlock=33629618 bestIsKBlock=true epoch=21769
t=2023-02-15T11:12:28+0000 lvl=info msg=-------------------------------------------------- pkg=pacemaker
t=2023-02-15T11:12:28+0000 lvl=info msg="  OnBeat Round:0, Height:33629619, Reason:Init " pkg=pacemaker
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb700f3]

goroutine 713 [running]:
github.com/meterio/meter-pov/consensus.(*Pacemaker).onNormalBeat(0xc00011e1a0, 0x132d20?, 0xc0?, 0x0)
        /home/ubuntu/meter-pov/consensus/pacemaker.go:635 +0x193
github.com/meterio/meter-pov/consensus.(*Pacemaker).OnBeat(0xc001d63e68?, 0x1d63dc8?, 0xc0?, 0x0?)
        /home/ubuntu/meter-pov/consensus/pacemaker.go:626 +0x65
github.com/meterio/meter-pov/consensus.(*Pacemaker).mainLoop(0xc00011e1a0)
        /home/ubuntu/meter-pov/consensus/pacemaker.go:1059 +0x1187
created by github.com/meterio/meter-pov/consensus.(*Pacemaker).Start
        /home/ubuntu/meter-pov/consensus/pacemaker.go:967 +0x75c
```

**Comment by simonzg** [comment]
`committee initialized already` usually indicates the env for pacemaker has been calculated before. Usually this is due to a race condition between commited kblock and synced kblock:

1. commited kblock generates a kblock info and append it to kblockInfoQueue, this got picked up and handled, and pacemaker is started, onBeat scheduled but not yet happened
2. synced kblock append a msg in `kblockInfoQueue` again, and this triggers the pacemaker for a full reset, and right before it's started
3. OnBeat from committed block is triggered, and now everything is empty and this OnBeat panics

This issue has been fixed in fd8145bdcfe041632ea62ed6b3ef4a3fb9ef6c06
